### ISSUE TITLE
Current pypi version fails while current GitHub master version works 

### ISSUE THREAD

**Issue by ctittel** [fabanc/pyvoronoi#18]
I have the following code in my project:
```python
points = pv.DiscretizeCurvedEdge(cell_edge, discretization_dist)
coords += [(p[0], p[1]) for p in list(points)]
```

When I use the pypi version of pyvoronoi, the second line fails with the error `ERROR:grpc._server:Exception calling application: 'cython_function_or_method' object does not support vectorcall`.

When I use the GitHub `master` version (installed via `pip3 install git+https://github.com/Voxel8/pyvoronoi.git`) everything works fine.

Please update the pypi version of pyvoronoi to include the changes from the last commit on master, it seems to be important.

**Comment by maxvoxel8** [comment]
I believe the pypi version is the latest version. The problem is the installation method. 

@fabanc are you still maintaining this repo? I can transfer it to you if you would like.

**Comment by fabanc** [comment]
Hi Max and Chris

I am still maintaining it. I am going to have a look at that right now so I
can fix it before I go on vacation tonight.

*Fabien*

**Comment by fabanc** [comment]
@ctittel I can confirm that pip and git have the same version. I spot no code change running a diff. Code runs fine on my Windows machine as well as the few workmates who use it. Can you give me:

- Your machine OS
- Your Python version.
- If you're using Anaconda or pure Python

I am going to regenerate new packages if need be when I am back, and give it a try with the same distribution that you. That will just have to wait a week. I would rather do that when I have  a bit more time

**Comment by ctittel** [comment]
Thanks!

I experienced the issue (that it fails with the pypi version and works when installing directly from GitHub) both on my main OS and within Docker containers. 

> Your machine OS

My Notebook and the Docker containers both used Ubuntu 20.04.

> Your Python version.

My Notebook uses Python 3.8.10.
The Docker containers use the current Python version from the Ubuntu archives (also Python 3.8)

> If you're using Anaconda or pure Python

pure Python, only pip for managing the dependencies

**Comment by fabanc** [comment]
Hi @ctittel ,

I am back, and I have fixed the package on pip. Installing from pip using python 3.8 should work. 

I want to make sure I solve the issue you're facing first. Make sure you're fetching version 1.0.7. That's the latest. If pip is still trying to install 1.0.5, you need to run pip install with the option `--no-cache-dir` 

Please let me know if the issue is solved for you. Once I have you're confirmation, I will push the latest setup file to github to the package version matches the one on pypi.

PS: I have set an demo for docker you can use there: https://github.com/fabanc/pyvoronoi-docker/blob/main/python-3x8/Dockerfile

**Comment by ctittel** [comment]
Hi @fabanc,

I just tried it and it's working now when installing from pypi, both on my system and within the Docker container.

Thanks! Closing the issue
